Blog.NTierMVC.Web/ViewComponents/LayoutFooterSocialMediaViewComponent.cs
using Blog.NTierMVC.Service.Service.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace Blog.NTierMVC.Web.ViewComponents
{
    public class LayoutFooterSocialMediaViewComponent : ViewComponent
    {
        private readonly ISocialMediaService mediaService;

        public LayoutFooterSocialMediaViewComponent(ISocialMediaService mediaService)
        {
            this.mediaService = mediaService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var socialMedias = await mediaService.GetAllSocialMediasNonDeleted();
            return View(socialMedias);
        }
    }
}

Blog.NTierMVC.Web/ViewComponents/LayoutHeaderSocialMediaViewComponent.cs
using Blog.NTierMVC.Service.Service.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace Blog.NTierMVC.Web.ViewComponents
{
    public class LayoutHeaderSocialMediaViewComponent : ViewComponent
    {
        private readonly ISocialMediaService mediaService;

        public LayoutHeaderSocialMediaViewComponent(ISocialMediaService mediaService)
        {
            this.mediaService = mediaService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var socialMedias = await mediaService.GetAllSocialMediasNonDeleted();
            return View(socialMedias);
        }
    }
}

Blog.NTierMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Blog.NTierMVC.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Blog.NTierMVC.Web.styles.css" asp-append-version="true" />
	<!-- Bootstrap core CSS -->
	<link href="~/stand-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


	<!-- Additional CSS Files -->
	<link rel="stylesheet" href="~/stand-blog/assets/css/fontawesome.css">
	<link rel="stylesheet" href="~/stand-blog/assets/css/templatemo-stand-blog.css">
	<link rel="stylesheet" href="~/stand-blog/assets/css/owl.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<!--

	TemplateMo 551 Stand Blog

	https://templatemo.com/tm-551-stand-blog

	-->
</head>
<body>
	<!-- ***** Preloader Start ***** -->
	<div id="preloader">
		<div class="jumper">
			<div></div>
			<div></div>
			<div></div>
		</div>
	</div>
	<!-- ***** Preloader End ***** -->
	<!-- Header -->
	<header class="">
		<nav class="navbar navbar-expand-lg">
			<div class="container">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index"><h2>@ViewData["Title"]<em>.</em></h2></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				@await Component.InvokeAsync("LayoutHeaderSocialMedia")
			</div>
		</nav>
	</header>

	@RenderBody()

	<footer>
		<div class="container">
			<div class="row">

				@await Component.InvokeAsync("LayoutFooterSocialMedia")

				<div class="col-lg-12">
					<div class="copyright-text">
						<p>
							Copyright 2020 Stand Blog Co.

							| Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="~/stand-blog/vendor/jquery/jquery.min.js"></script>
	<script src="~/stand-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Additional Scripts -->
	<script src="~/stand-blog/assets/js/custom.js"></script>
	<script src="~/stand-blog/assets/js/owl.js"></script>
	<script src="~/stand-blog/assets/js/slick.js"></script>
	<script src="~/stand-blog/assets/js/isotope.js"></script>
	<script src="~/stand-blog/assets/js/accordions.js"></script>

	<script language="text/Javascript">
		cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
		function clearField(t) {                   //declaring the array outside of the
			if (!cleared[t.id]) {                      // function makes it static and global
				cleared[t.id] = 1;  // you could use true and false, but that's more typing
				t.value = '';         // with more chance of typos
				t.style.color = '#fff';
			}
		}
	</script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>